image: node:12

services:
  - postgres:latest

variables:
  POSTGRES_DB: wikidb
  POSTGRES_USER: wikid
  POSTGRES_PASSWORD: wikid
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - install
  - build+test

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/
      - ./*/node_modules/

build:
  stage: build+test
  script:
    - yarn docker:build && docker push registry.gitlab.com/ivasilov/wikid

test:backend:
  stage: build+test
  script:
    - yarn workspace backend run test

test:frontend:
  stage: build+test
  script:
    - yarn workspace frontend run test
