image: node:12

services:
  - postgres:latest

stages:
  - install
  - build+test

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build+test
  script:
    - yarn build

test:backend:
  stage: build+test
  script:
    - yarn workspace backend run test:e2e

test:backend:e2e:
  stage: build+test
  script:
    - yarn workspace backend run test:e2e

test:frontend:
  stage: build+test
  script:
    - yarn workspace frontend run test
