version: '3.4'
services:
  wikid:
    container_name: wikid
    image: registry.gitlab.com/ivasilov/wikid
    restart: unless-stopped
    network_mode: host
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=localhost
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=wikid
      - TYPEORM_PASSWORD=wikid
      - TYPEORM_DATABASE=wikidb
      - TYPEORM_LOGGING=true
      - TYPEORM_ENTITIES=backend/build/**/entity.js
      - TYPEORM_MIGRATIONS_DIR=backend/build/**/migrations/*.js
      - TYPEORM_MIGRATIONS_TABLE_NAME=migrations

  postgres:
    container_name: postgres
    image: postgres:11
    restart: unless-stopped
    network_mode: host
    environment:
      - POSTGRES_USER=wikid
      - POSTGRES_PASSWORD=wikid
      - POSTGRES_DB=wikidb
      - POSTGRES_PORT=5433
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data:
