version: '3.4'
services:
  wikid:
    container_name: wikid
    image: registry.gitlab.com/ivasilov/wikid:master
    restart: unless-stopped
    network_mode: host
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=localhost
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=wikid
      - TYPEORM_PASSWORD=wikid
      - TYPEORM_DATABASE=wikidb
      - TYPEORM_LOGGING=true
      - TYPEORM_ENTITIES=backend/build/**/entity.js
      - TYPEORM_MIGRATIONS_RUN=true
      - TYPEORM_MIGRATIONS=backend/build/**/migrations/*.js
      - TYPEORM_MIGRATIONS_TABLE_NAME=migrations

  postgres:
    container_name: postgres
    image: postgres:11
    restart: unless-stopped
    network_mode: host
    environment:
      - POSTGRES_USER=wikid
      - POSTGRES_PASSWORD=wikid
      - POSTGRES_DB=wikidb
      - POSTGRES_PORT=5432
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true # delete old images after restart
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --cleanup

volumes:
  database-data:
