default: # default connection
  'type': 'postgres'
  'host': 'localhost'
  'port': 5432
  'username': 'wikid'
  'password': 'wikid'
  'database': 'wikidb'
  'logging': ["schema", "warn", "error"]
  'entities': ['build/**/entity.js']
  'migrations': ['build/**/migrations/*.js']
  'migrationsRun': true
  'migrationsTableName': 'migrations'
