export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const BOOKMARKS_REPOSITORY = 'BOOKMARKS_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const PAGES_REPOSITORY = 'PAGES_REPOSITORY';

export const JWT_SECRET_KEY = 'TEST_KEY';

export const TRANSACTION_MANAGER_KEY = Symbol('TRANSACTION_MANAGER');
export const REQUEST_CONTEXT_KEY = Symbol('WIKID_REQUEST_CONTEXT_KEY');
